### ISSUE TITLE
How do I install extras?

### ISSUE THREAD

**Issue by muscovitebob** [conda-forge/apache-beam-feedstock#40]
At the moment it is unclear to me how I would for example do the equivalent of `pip install apache-beam[gcp]` using this feedstock, is this possible?

**Comment by xylar** [comment]
@muscovitebob, I'm going to re-open this.  Thank you for opening the issue.

We do have a way of handling extras.  You can take a look at the [apache-airflow feedstock](https://github.com/conda-forge/airflow-feedstock) as an example.  What we would do in this case is create a package called `apache-beam-with-gcp` that would include the same version of `apache-beam` along with the extras.  I hadn't done this so far because I wasn't sure how much demand there was for it and because it's a decent amount of work to maintain.  But your request is enough for me to know that it's something of interest.

I can also take care of making a recipe for `google-cloud-recommendations-ai` so conda-forge will support that package.  I will leave this issue open until I've taken care of both of those.

**Comment by xylar** [comment]
I have a recipe on staged recipes:
https://github.com/conda-forge/staged-recipes/pull/16260
but it needs:
https://github.com/conda-forge/libcst-feedstock/pull/24

That same fix is also needed for other dependencies of `apache-beam-with-gcp` in my local testing.
